### ISSUE TITLE
module "Toou2D" is not installed

### ISSUE THREAD

**Issue by xuin-net** [ShowFL/Toou-2D#1]
![image](https://user-images.githubusercontent.com/12799071/61720074-b97b2380-ad98-11e9-8607-29e74efffee3.png)
qt 5.13.0 mac build gets fatal error: module "Toou2D" is not installed

**Comment by ShowFL** [comment]
Very interesting. It's been solved.

**Comment by ShowFL** [comment]
https://github.com/ShowFL/Toou-2D/blob/46310d7490cf11c8875879d3a4fe3e82b2d1775e/.gitignore#L30
