### ISSUE TITLE
你好，在android上跑出现以下错误：

### ISSUE THREAD

**Issue by Liu-Eleven** [ShowFL/Toou-2D#4]
W libexample.so: qrc:/main.qml:6 module "Toou2D" plugin "Toou2D" not found
请问该怎么解决啊？

**Comment by ShowFL** [comment]
请问是运行T2d demo吗？
请检查Qt 安装目录Toou2D是否已经安装成功，Toou2D是否存在。
例如：Qt5.9.7/5.9.7/android_armv7/qml/Toou2D

我们测试 macos 系统下构建是通过的。而且他运行的非常完美。
[可以来QQ群询问](https://github.com/ShowFL/Toou-2D#找到我们)

**Comment by ShowFL** [comment]
![F0C87D47D1B667DF267D3B7C1D65E0C1](https://user-images.githubusercontent.com/9900479/61942887-dac45580-afcc-11e9-9739-103fa91c81f5.jpg)

**Comment by ShowFL** [comment]
已经修复
https://github.com/ShowFL/Toou-2D/tree/v1.0
感谢您的反馈

**Comment by Liu-Eleven** [comment]
你好，类似这种错误我自己再开发中也会遇到。当我想把自己写好的qml控件导出为库时也会遇到这种问题，请问应该怎么才能正确的解决？




------------------ 原始邮件 ------------------
发件人: "Toou"<notifications@github.com>;
发送时间: 2019年9月16日(星期一) 上午9:26
收件人: "ShowFL/Toou-2D"<Toou-2D@noreply.github.com>;
抄送: "刘一儿"<1024847801@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ShowFL/Toou-2D] 你好，在android上跑出现以下错误： (#4)




已经修复
 https://github.com/ShowFL/Toou-2D/tree/v1.0
 感谢您的反馈
