### ISSUE TITLE
cmake 构建脚本

### ISSUE THREAD

**Issue by ijinjay** [ShowFL/Toou-2D#9]
您好，我想将您这个项目通过cmake方式构建，下面这个gist里包含了我构建使用的CMakeLists.txt和相关文件，程序在Linux下可以正常构建并运行，而在Mac 下能够构建成功却始终不能运行，调了好久不知道在哪里有问题，希望您能够指导指导。 😃 期待您的回复。

[Toou2D cmake](https://gist.github.com/ijinjay/696ef075e68c23357cb2844254e22985)文件结构如下:
```
CMakeLists.txt
cmake
     |--Functions.cmake
     |--info.plist.in
     |--meta_Toou2D.hpp.in
icons
     |--develop
     |          |--Toou2DExample.icns
     |--release
     |          |--Toou2DExample.icns
     |--testing
                |--Toou2DExample.icns
```

**Comment by ShowFL** [comment]
你可以参考一下 412165786 的fork版本
https://github.com/412165786/Toou-2D/commit/031b6bd271b215661bbe897df1c82251eb95da3e
